# -*- coding: utf-8 -*-
"""Data science exp.  1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sgC-dP3lKHYjF4XOBW8xm4vidV9pXej8
"""

# Using + operator :-
first_name = "Shivam"
last_name = " Sahu"
name = first_name + last_name
print(name)

# Using .join operator :-
var1 = "Shivam"
var2 = " Sahu"
print("".join([var1,var2]))

# Using % operator :-
A = "Civil"
B = " Engineering"
print("%s%s"%(A,B))

# Using format() :-
coll = "MITS"
city = "Gwalior"
print("{} {}".format(coll,city))

# Using "," operator :-
sub = "Data Science,"
sem = "5th semester,"
prof = "Dr. Abhilash Shukla"
print(sub, sem, prof)